name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: docker image list\
      - name: pull image
        run: docker pull mariadb
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      
